const ROLES = {
  SANEAMIENTO: 'SANEAMIENTO',
  MANTENIMIENTO: 'MANTENIMIENTO',
  CALIDAD: 'CALIDAD',
  PROCESOS: 'PROCESOS',
  ADMIN: 'ADMIN',
};

const SERVICE_ERRORS = {
  MISSING_ID: 'MISSING_ID',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
};

module.exports = {
  ROLES,
  SERVICE_ERRORS,
};
